### ISSUE TITLE
卸下插件GeoHey-Toolbox时出错 

### ISSUE THREAD

**Issue by sys2007** [sshuair/geohey-toolbox#4]
卸下插件GeoHey-Toolbox时出错 
KeyError: 'GeoHey-Toolbox' 
Traceback (most recent call last):
  File "d:/Program Files/QGIS 3.0/apps/qgis/./python\qgis\utils.py", line 394, in unloadPlugin
    _unloadPluginModules(packageName)
  File "d:/Program Files/QGIS 3.0/apps/qgis/./python\qgis\utils.py", line 405, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: 'GeoHey-Toolbox'

Python版本： 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS版本： 3.0.2-Girona Girona, 307d082e3d

**Comment by sshuair** [comment]
Fixed, try again

**Comment by sshuair** [comment]
问题我关闭了，如果还有问题，请联系我
